#include "ExportService.h"
#include "core/AppSettings.h"
#include "utils/Money.h"

#include <QFile>
#include <QPrintDialog>
#include <QPrinter>
#include <QPrinterInfo>
#include <QTextDocument>
#include <QTextStream>

#ifdef EB_HAS_XLSX
#include "xlsxdocument.h"
#endif

namespace eb {

static QString csvEscape(QString s)
{
    if (s.contains(',') || s.contains('"') || s.contains('\n'))
        s = '"' + s.replace('"', "\"\"") + '"';
    return s;
}

bool ExportService::exportCsv(const QString &file, const QVector<ReportRow> &rows)
{
    QFile f(file);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) {
        m_lastError = f.errorString();
        return false;
    }
    QTextStream ts(&f);
    ts << "Date,Employee,Category,Sub Category,Description,Payment Method,Reference,Amount\n";
    for (const ReportRow &r : rows) {
        ts << r.date.toString(Qt::ISODate) << ','
           << csvEscape(r.employee) << ',' << csvEscape(r.category) << ','
           << csvEscape(r.subCategory) << ',' << csvEscape(r.description) << ','
           << csvEscape(r.method) << ',' << csvEscape(r.reference) << ','
           << QString::number(r.amountCents / 100.0, 'f', 2) << '\n';
    }
    return true;
}

bool ExportService::exportXlsx(const QString &file, const QVector<ReportRow> &rows)
{
#ifdef EB_HAS_XLSX
    QXlsx::Document doc;
    const QStringList headers{"Date", "Employee", "Category", "Sub Category",
                              "Description", "Payment Method", "Reference", "Amount"};
    for (int c = 0; c < headers.size(); ++c)
        doc.write(1, c + 1, headers[c]);
    int row = 2;
    qint64 total = 0;
    for (const ReportRow &r : rows) {
        doc.write(row, 1, r.date.toString(Qt::ISODate));
        doc.write(row, 2, r.employee);
        doc.write(row, 3, r.category);
        doc.write(row, 4, r.subCategory);
        doc.write(row, 5, r.description);
        doc.write(row, 6, r.method);
        doc.write(row, 7, r.reference);
        doc.write(row, 8, r.amountCents / 100.0);
        total += r.amountCents;
        ++row;
    }
    doc.write(row, 7, "TOTAL");
    doc.write(row, 8, total / 100.0);
    if (!doc.saveAs(file)) {
        m_lastError = "Could not write " + file;
        return false;
    }
    return true;
#else
    Q_UNUSED(file); Q_UNUSED(rows);
    m_lastError = "Built without XLSX support (enable EB_WITH_XLSX).";
    return false;
#endif
}

QString ExportService::ledgerHtml(const QString &title, const QVector<ReportRow> &rows)
{
    const auto &s = AppSettings::instance();
    qint64 total = 0;
    QString body;
    int i = 0;
    for (const ReportRow &r : rows) {
        total += r.amountCents;
        body += QString(
            "<tr style='background:%1'>"
            "<td>%2</td><td>%3</td><td>%4</td><td>%5</td><td>%6</td>"
            "<td>%7</td><td>%8</td><td align='right'>%9</td></tr>")
            .arg(i++ % 2 ? "#f4f6f8" : "#ffffff",
                 r.date.toString("dd MMM yyyy"), r.employee.toHtmlEscaped(),
                 r.category.toHtmlEscaped(), r.subCategory.toHtmlEscaped(),
                 r.description.toHtmlEscaped(), r.method.toHtmlEscaped(),
                 r.reference.toHtmlEscaped(), money::format(r.amountCents));
    }
    return QString(
        "<html><body style='font-family:Arial, sans-serif; font-size:9pt;'>"
        "<h2 style='margin-bottom:0'>%1</h2>"
        "<h3 style='margin-top:2px; color:#444'>%2</h3>"
        "<table width='100%' cellspacing='0' cellpadding='4' "
        "style='border:1px solid #999'>"
        "<tr style='background:#2b579a; color:white'>"
        "<th align='left'>Date</th><th align='left'>Employee</th>"
        "<th align='left'>Category</th><th align='left'>Sub Category</th>"
        "<th align='left'>Description</th><th align='left'>Method</th>"
        "<th align='left'>Ref #</th><th align='right'>Amount (%3)</th></tr>"
        "%4"
        "<tr><td colspan='7' align='right'><b>TOTAL</b></td>"
        "<td align='right'><b>%5</b></td></tr>"
        "</table><p style='color:#666'>Generated by ExpenseBook — %6 rows</p>"
        "</body></html>")
        .arg(s.companyName().toHtmlEscaped(), title.toHtmlEscaped(),
             s.currencySymbol(), body, money::format(total),
             QString::number(rows.size()));
}

bool ExportService::exportPdf(const QString &file, const QString &title,
                              const QVector<ReportRow> &rows)
{
    QPrinter printer(QPrinter::HighResolution);
    printer.setOutputFormat(QPrinter::PdfFormat);
    printer.setOutputFileName(file);
    printer.setPageOrientation(QPageLayout::Landscape);
    QTextDocument doc;
    doc.setHtml(ledgerHtml(title, rows));
    doc.print(&printer);
    return true;
}

bool ExportService::printReport(QWidget *parent, const QString &title,
                                const QVector<ReportRow> &rows)
{
    QPrinter printer(QPrinter::HighResolution);
    const QString preferred = AppSettings::instance().defaultPrinter();
    if (!preferred.isEmpty())
        printer.setPrinterName(preferred);
    printer.setPageOrientation(QPageLayout::Landscape);

    QPrintDialog dlg(&printer, parent);
    if (dlg.exec() != QDialog::Accepted)
        return false;
    QTextDocument doc;
    doc.setHtml(ledgerHtml(title, rows));
    doc.print(&printer);
    return true;
}

} // namespace eb
